version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: calendar-db
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: test24password
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
